FROM node:20-alpine AS frontend

WORKDIR /app

COPY ./apps/frontend/package.json ./
COPY ./apps/frontend/{{LOCK_FILE}} ./
RUN {{INSTALL_CMD}}

COPY ./apps/frontend .

EXPOSE 5173

CMD [ {{RUN_CMD_LIST}} ]