FROM node:20-alpine AS api

WORKDIR /app

WORKDIR /app/packages/domain
COPY ./packages/domain/package.json ./
COPY ./packages/domain/{{LOCK_FILE}} ./
RUN {{INSTALL_CMD}}


WORKDIR /app/apps/api
COPY ./apps/api/package.json ./
COPY ./apps/api/{{LOCK_FILE}} ./
RUN {{INSTALL_CMD}}


WORKDIR /app
COPY . .


WORKDIR /app/packages/domain
RUN {{BUILD_CMD}}


WORKDIR /app/apps/api
RUN {{BUILD_CMD}}

EXPOSE 8000

CMD ["node", "dist/index.js"]